[package]
name = "ThGorgeForHabr"
version = "0.1.0"
authors = ["All pcPowerJG <koito_tyan@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2"
[build-dependencies]
cc = "1.0"